name: Run Danger

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew ktlint
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: message
        run: echo "message=[info][title](beer)Danger Worked![/title]${GITHUB_REPOSITORY}[/info]" >> $GITHUB_OUTPUT
      - uses: okuzawats/chatwork-messaging-action@v1.0
        with:
          apiToken: ${{ secrets.API_KEY }}
          roomId: ${{ secrets.ROOM_ID }}
          message: ${{ steps.message.outputs.message }}
